import { Box, Container } from '@mui/material';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${inter.className} dawd`}>
        <Container sx={{ my: 5 }}>
          <Box textAlign="center" display="flex" flexDirection="column" alignItems="center">
            <main>{children}</main>
          </Box>
        </Container>
      </body>
    </html>
  );
}
